version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully"
      - node src/index.js

artifacts:
  files:
    - src/index.js
    - package.json
    - README.md
  discard-paths: yes
  base-directory: src
  destination: your-s3-bucket-name/your-folder-name/