version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
artifacts:
  files:
    - "**/*" # Include all files in the build output
  base-directory: experiment-aws-codebuild-bucket # Replace "build" with the directory containing your build output
  discard-paths: no
  # destination: experiment-aws-codebuild-bucket/
  # destination: your-s3-bucket-name/your-folder-name/